config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  devise_for :users
 root 'welcome#index'

  get 'welcome/about' 
  get 'meetings/new'
  post 'meetings/new'
  get 'meetings/create'
  post 'meetings/create'

  get 'meetings/index'
  post 'meetings/index'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base

belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


 has_many :meetings        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :username, :email, 
    :password, :password_confirmation) }

   devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :username, :email, 
    :password, :password_confirmation, :current_password) }
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
    @meeting.username = current_user.username
    @meeting.save


     
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.username = current_user.username
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end

    
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    
    respond_to do |format|

    
      if @meeting.update(meeting_params)
       
      

        # sets the time of the reservation based on the selection of practice or game

          if meeting_params["block"] == "Practice"
            @meeting.end_time = @meeting.start_time + 2.hours
          else
            @meeting.end_time = @meeting.start_time + 3.hours
          end  
          
          @meeting.save
          

          format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
          format.json { render :show, status: :ok, location: @meeting }
        
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
      
     end

    end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time, :username, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@meetings = Meeting.all
		
	end		

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TennisReserve</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Tangerine:700' rel='stylesheet' type='text/css'>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a> -->
    </div> 

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#"><span class="sr-only">(current)</span></a></li>
        <li><%= link_to "Home", root_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reservations <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Make a reservation", meetings_new_path %></li>
            <li><%= link_to "See your reservations", meetings_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
       <li><%= link_to "Edit Profile", edit_user_registration_path %></li> 
       <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% end %>

        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li> -->
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>





<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
   <p> Is this a practice or game: <%= select_tag :block, options_for_select([ "Practice", "Game" ]), :prompt => "Please select" %></p>
  </div>



  <div class="field">
    <%= f.label :created_by%><br>
    <%= current_user.username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
    <div class="row">

      <div class="col-lg-6">
				
				<div class="well">
					<h1>Edit Reservation</h1>

					<%= render 'form' %>

					<%= link_to 'Show', @meeting, class: 'btn btn-info' %> 
					<%= link_to 'Back', meetings_path, class: 'btn btn-sucess' %>
			</div>
		</div>			
	</div>	

app/views/meetings/index.html.erb
<div class="well" style="background: rgba(255, 255, 255, 0.5);">
  <p id="notice"><%= notice %></p>

    <h2>Reservations created by <%= current_user.username %></h2>

    

      
        <% @meetings.each do |meeting| %>
         <% if meeting.username == current_user.username %>
              <%if meeting.start_time != nil %>
        
          <div class="row">
              <div class="col-md-5">
              <div class="well"> 
              <ul>
                <li><strong><%= meeting.name %></strong></li>
                <%= meeting.start_time.strftime(" %A, %B %d, %Y") %><br />
                <%= meeting.start_time.strftime("%I:%M%p") %> - 
                <%= meeting.end_time.strftime("%I:%M%p") %><br /> 
                
                
                <%= link_to 'Show', meeting, class: 'btn btn-success'  %> |
                <%= link_to 'Edit', edit_meeting_path(meeting), class: 'btn btn-warning'  %> |
                <%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
              </ul>
              </div>
            </div>
          </div>
          <% end %>
         <% end %>
        <% end %>
      
 

    <br>

    <%= link_to 'New Meeting', new_meeting_path, class: 'btn btn-info' %>
  </div>  

app/views/meetings/new.html.erb
<div class="well">

    <div class="row">

      <div class="col-lg-4">

				<h1>New Reservation</h1>

				<%= render 'form' %>

				<%= link_to 'Back', meetings_path, class: 'btn btn-info' %>
				
			</div>
		</div>
</div>				

app/views/meetings/show.html.erb
<div class="row">
<div class="col-lg-8">
    <div class="well">

      

<p id="notice"><%= notice %></p>


<h3><em> Your reservation is set!  Please make a note on your calendar. Reservations are forfeited after 15 minutes. </em></h3>
<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>


<!-- puts the date in Day, Month date, year format -->
		<p>
		<strong>Date: </strong>
		<%= @meeting.start_time.strftime("%A, %B %d, %Y") %>
		</p>

		<p>
		  <strong>Start time:</strong>
		  <%= @meeting.start_time.strftime("%I:%M%p") %> 
		     
		</p>

		<p>
		  <strong>End time:</strong>
		  <%= @meeting.end_time.strftime("%I:%M%p") %>
		</p>

		<p>
		  <strong>Username:</strong>
		  <%= @meeting.username %>
		</p>


<%= link_to 'Edit', edit_meeting_path(@meeting), class: 'btn btn-warning' %> |
<%= link_to 'Back', meetings_path, class: 'btn btn-success' %>

</div>
</div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <%= link_to "Previous", url_for(params.merge(start_date: date_range.first - 1.day)) %>
  <%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %>
  <%= link_to "Next", url_for(params.merge(start_date: date_range.last + 1.day)) %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="well", style="background: rgba(255, 255, 255, 0.7);); ">

<div class="simple-calendar">
  <%= link_to "Previous", url_for(params.merge(start_date: date_range.first - 1.day)) %>
  <%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %>
  <%= link_to "Next", url_for(params.merge(start_date: date_range.last + 1.day))  %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <%= link_to "Previous", url_for(params.merge(start_date: date_range.first - 1.day)) %>
  Week <%= start_date.strftime("%U").to_i %>
  <%= link_to "Next", url_for(params.merge(start_date: date_range.last + 1.day)) %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="jumbotron" style="text-align: center;">
<div class="well">
	<div class="col-lg-8">
<h2> Welcome to the Bentley Park Tennis Courts </h2>
  </div>
  <div class="col-lg-4">
<p><%= image_tag "bp_front.jpg", alt: "Bentley Park Front" , width: "250" %></p>
</div>
<div style="text-align: center;" >
<p>See a list of our events below </p>
</div>
</div>
</div>

<!-- remove nil entries -->

<% @meetings.each do |m| %>
    <% if m.start_time == nil %>
      <%  m.delete  %>
    <% end %>
<% end %>
<!-- end of removal -->

<%= month_calendar events: @meetings do |date, meetings| %>
  <%= date.strftime("%d") %>

  <% meetings.each do |meeting| %>
    <div>
      <strong><%= meeting.name %></strong><br/>
      <%= meeting.start_time.strftime("%I:%M%p") %> - <br/>
      <%= meeting.end_time.strftime("%I:%M%p") %><br/>
      Created by: <%= meeting.username %>
    </div>
  <% end %>
<% end %>